services:
  - type: web
    name: backend
    runtime: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ModlinkProduction
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings.production


databases:
  - name: ModlinkProduction
    databaseName: modlinkproduction
    user: modlinkproduction_user
